---
build_from:
  aarch64: ghcr.io/erik73/base-python/aarch64:4.0.3
  amd64: ghcr.io/erik73/base-python/amd64:4.0.3
  armhf: ghcr.io/erik73/base-python/armhf:4.0.3
  armv7: ghcr.io/erik73/base-python/armv7:4.0.3
  i386: ghcr.io/erik73/base-python/i386:4.0.3
