---
build_from:
  aarch64: ghcr.io/erik73/base-python/aarch64:2.0.9
  amd64: ghcr.io/erik73/base-python/amd64:3.0.1
  armhf: ghcr.io/erik73/base-python/armhf:2.0.9
  armv7: ghcr.io/erik73/base-python/armv7:2.0.9
  i386: ghcr.io/erik73/base-python/i386:3.0.1
