---
build_from:
  aarch64: ghcr.io/erik73/base-python/aarch64:3.0.11
  amd64: ghcr.io/erik73/base-python/amd64:3.0.11
  armhf: ghcr.io/erik73/base-python/armhf:3.0.11
  armv7: ghcr.io/erik73/base-python/armv7:3.0.11
  i386: ghcr.io/erik73/base-python/i386:3.0.11
